# Generated by Django 3.1.7 on 2021-04-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='AccountActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='SmartStox',
            field=models.BooleanField(default=False),
        ),
    ]
