# Generated by Django 3.1.7 on 2021-04-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210408_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='UserImage',
            field=models.ImageField(blank=True, null=True, upload_to='UserImages'),
        ),
    ]
