# Generated by Django 3.1.7 on 2021-04-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_authentication_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='Notifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
